name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Enable source repositories
        run: |
          echo "deb-src http://azure.archive.ubuntu.com/ubuntu/ noble main universe restricted multiverse" | sudo tee -a /etc/apt/sources.list
          echo "deb-src http://azure.archive.ubuntu.com/ubuntu/ noble-updates main universe restricted multiverse" | sudo tee -a /etc/apt/sources.list
          echo "deb-src http://azure.archive.ubuntu.com/ubuntu/ noble-security main universe restricted multiverse" | sudo tee -a /etc/apt/sources.list
          sudo apt-get update

      - name: Install GDAL dependencies
        run: |
          sudo apt-get install -y build-essential
          sudo apt-get build-dep gdal
          wget https://download.osgeo.org/gdal/3.11.0/gdal-3.11.0.tar.gz
          tar -xzf gdal-3.11.0.tar.gz
          cd gdal-3.11.0
          ./configure
          make
          sudo make install

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          python -m unittest discover -s tests
